/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thietke_agile;

import java.awt.Desktop;

/**
 *
 * @author Admin
 */
public class FormBanHang extends javax.swing.JFrame {

    /**
     * Creates new form FormBanHang
     */
    public FormBanHang() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        Desktop = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnDangNhap = new javax.swing.JMenu();
        jmnDangKy = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmnDoanhThu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmnSanPham = new javax.swing.JMenuItem();
        jmnBanhang = new javax.swing.JMenuItem();
        jmnKhachHang = new javax.swing.JMenu();
        jmnSoSanh = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        Desktop.setBackground(new java.awt.Color(0, 153, 153));
        Desktop.setForeground(new java.awt.Color(0, 204, 204));
        Desktop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1559, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmnDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        jmnDangNhap.setForeground(new java.awt.Color(255, 0, 0));
        jmnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login (1).png"))); // NOI18N
        jmnDangNhap.setText("Đăng nhập");
        jmnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnDangNhapMouseClicked(evt);
            }
        });
        jmnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDangNhapActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmnDangNhap);

        jmnDangKy.setForeground(new java.awt.Color(255, 0, 0));
        jmnDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registration (1).png"))); // NOI18N
        jmnDangKy.setText("Đăng ký");
        jmnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmnDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnDangKyMouseClicked(evt);
            }
        });
        jmnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDangKyActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmnDangKy);

        jMenu3.setForeground(new java.awt.Color(255, 0, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buy.png"))); // NOI18N
        jMenu3.setText("Bán hàng");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });

        jmnDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmnDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmnDoanhThu.setForeground(new java.awt.Color(255, 0, 0));
        jmnDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/money.png"))); // NOI18N
        jmnDoanhThu.setText("Quản lý doanh thu");
        jmnDoanhThu.setFocusable(true);
        jmnDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnDoanhThuMouseClicked(evt);
            }
        });
        jmnDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDoanhThuActionPerformed(evt);
            }
        });
        jMenu3.add(jmnDoanhThu);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delivery.png"))); // NOI18N
        jMenuItem2.setText("Danh sách đơn hàng");
        jMenuItem2.setFocusable(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jmnSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmnSanPham.setForeground(new java.awt.Color(255, 0, 0));
        jmnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/product.png"))); // NOI18N
        jmnSanPham.setText("Quản lý sản phẩm");
        jmnSanPham.setFocusable(true);
        jmnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnSanPhamMouseClicked(evt);
            }
        });
        jmnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnSanPhamActionPerformed(evt);
            }
        });
        jMenu3.add(jmnSanPham);

        jmnBanhang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmnBanhang.setForeground(new java.awt.Color(255, 0, 0));
        jmnBanhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sell.png"))); // NOI18N
        jmnBanhang.setText("Bán hàng");
        jmnBanhang.setFocusable(true);
        jmnBanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnBanhangActionPerformed(evt);
            }
        });
        jMenu3.add(jmnBanhang);

        jMenuBar1.add(jMenu3);

        jmnKhachHang.setForeground(new java.awt.Color(255, 0, 0));
        jmnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer.png"))); // NOI18N
        jmnKhachHang.setText("Khách hàng");
        jmnKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnKhachHangMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmnKhachHang);

        jmnSoSanh.setForeground(new java.awt.Color(255, 0, 0));
        jmnSoSanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/law.png"))); // NOI18N
        jmnSoSanh.setText("So sánh");
        jmnSoSanh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmnSoSanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnSoSanhMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmnSoSanh);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDoanhThuActionPerformed
        FormDoanhThu frm = new FormDoanhThu();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnDoanhThuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormDonHang frm = new FormDonHang();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnSanPhamActionPerformed
        FormSanPham frm = new FormSanPham();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnSanPhamActionPerformed

    private void jmnBanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnBanhangActionPerformed
         FormBH frm = new FormBH();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnBanhangActionPerformed

    private void jmnSoSanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnSoSanhMouseClicked
         FormSoSanh frm = new FormSoSanh();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnSoSanhMouseClicked

    private void jmnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDangKyActionPerformed
        
    }//GEN-LAST:event_jmnDangKyActionPerformed

    private void jmnDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnDangKyMouseClicked
        FormDangKy frm = new FormDangKy();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnDangKyMouseClicked

    private void jmnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnSanPhamMouseClicked
        FormSanPham frm = new FormSanPham();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnSanPhamMouseClicked

    private void jmnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnKhachHangMouseClicked
        FormKhachHang frm = new FormKhachHang();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnKhachHangMouseClicked

    private void jmnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDangNhapActionPerformed
        FormDangNhap frm = new FormDangNhap();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnDangNhapActionPerformed

    private void jmnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnDangNhapMouseClicked
        FormDangNhap frm = new FormDangNhap();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnDangNhapMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jmnDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnDoanhThuMouseClicked
        FormDoanhThu frm = new FormDoanhThu();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jmnDoanhThuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desktop;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jmnBanhang;
    private javax.swing.JMenu jmnDangKy;
    private javax.swing.JMenu jmnDangNhap;
    private javax.swing.JMenuItem jmnDoanhThu;
    private javax.swing.JMenu jmnKhachHang;
    private javax.swing.JMenuItem jmnSanPham;
    private javax.swing.JMenu jmnSoSanh;
    // End of variables declaration//GEN-END:variables
}
